name: Create release branch

on:
  # DEBUGGING: switch to on tag creation
  push:
    branches:
    - release-branch-test

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.repository == 'envoyproxy/envoy'
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Create release branch
        run: ./ci/create_release_branch.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
